# The Docker image to run your workspace in. Defaults to gitpod/workspace-full
image:
  file: 
    .gitpod.Dockerfile

#tasks:
#  - init: yarn install
#  - command: yarn build
#  - command: "npm install && npm run serve"
# 
# Ports to expose on workspace startup (optional)
ports:
  - port: 8000
    onOpen: open-preview

# 
# Command to add your extensions
vscode:
  extensions:
    - formulahendry.code-runner@0.9.17:/CI2LS8o4IE980vinLu1Yg==
    - vscode-icons-team.vscode-icons@9.7.0:vWMZFN0zy+UAVL2V5iuz4A==
    - formulahendry.dotnet-test-explorer@0.7.1:aMBBHLwB96Y4mOqZ8ucTKw==
    - redhat.vscode-yaml@0.6.1:Lngx1V8Nd6ig2dgVcDntyQ==
    - adrianwilczynski.asp-net-core-switcher@2.0.2:/OcpAa9EZqn0U4NG+fDHpg==# 
    - adrianwilczynski.asp-net-core-snippet-pack@1.50.2:D1uvqtKCfzRNI6pITs3iXw==# Command to start on workspace startup (optional)
    - leo-labs.dotnet@1.0.3:YR8ZjeV+0/Ut87luga8WGw==